# Generated by Django 3.2.3 on 2021-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Enter ID', max_length=15)),
                ('upassword', models.CharField(help_text='Enter password', max_length=20)),
                ('name', models.CharField(help_text='Enter your name', max_length=20)),
                ('type', models.CharField(choices=[('DO', 'Doctor'), ('PA', 'Patient')], max_length=2)),
                ('location', models.CharField(help_text='Enter your location', max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
